declare const Deno: { env: { get(name: string): string | undefined }; serve(handler: (req: Request)=>Response|Promise<Response>): void };

type Row = Record<string, any>;
const VERSION="1.0.0", SERVICE="ct.pentabooks.control.v1";
const U=Deno.env.get("SUPABASE_URL")??"", K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"", REST=`${U}/rest/v1`;
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const out=(s:number,b:unknown)=>new Response(JSON.stringify(b),{status:s,headers:H});
const headers=()=>({apikey:K,authorization:`Bearer ${K}`,"content-type":"application/json",prefer:"return=representation"});
const text=(v:unknown,n=500)=>typeof v==="string"?v.trim().slice(0,n):"";
const obj=(v:unknown):Row=>v&&typeof v==="object"&&!Array.isArray(v)?v as Row:{};
const id=(v:unknown)=>{const s=text(v,80);if(!/^[0-9a-f-]{20,80}$/i.test(s))throw Error("invalid_id");return s};
const integer=(v:unknown,d:number|null=null)=>Number.isFinite(Number(v))?Math.trunc(Number(v)):d;
async function db(path:string,init:RequestInit={}){if(!U||!K)throw Error("PENTABOOKS_RUNTIME_NOT_CONFIGURED");const r=await fetch(`${REST}/${path}`,{...init,headers:{...headers(),...(init.headers??{})}}),t=await r.text();if(!r.ok)throw Error(`DB_${r.status}:${t.slice(0,280)}`);return t?JSON.parse(t):null}
const get=(path:string)=>db(path,{method:"GET"});
const post=(table:string,row:Row)=>db(table,{method:"POST",body:JSON.stringify(row)});
const upsert=(table:string,row:Row,conflict:string)=>db(`${table}?on_conflict=${encodeURIComponent(conflict)}`,{method:"POST",headers:{prefer:"resolution=merge-duplicates,return=representation"},body:JSON.stringify(row)});
async function event(event_type:string,aggregate_type:string,aggregate_id:string,payload:Row={}){return (await post("penta_book_events",{event_type,aggregate_type,aggregate_id,payload,delivery_state:"pending"}))?.[0]??null}
async function health(){const [state,books,editions,pending]=await Promise.all([get("penta_book_system_state?system_key=eq.pentabooks&select=*"),get("penta_books?select=id"),get("penta_book_editions?select=id"),get("penta_book_events?delivery_state=eq.pending&select=id")]);return{ok:true,service:SERVICE,version:VERSION,state:state?.[0]??null,counts:{books:books?.length??0,editions:editions?.length??0,pending_events:pending?.length??0}}}
async function catalog(){return{ok:true,service:SERVICE,version:VERSION,books:await get("penta_books?select=id,slug,title,universe,series,book_number,creator,imprint,canonical_status,maturity,metadata,updated_at&order=universe.asc,book_number.asc.nullslast,title.asc"),editions:await get("penta_book_editions?select=id,book_id,version,edition_name,format,status,vm_standard,page_count,word_count,illustration_count,rights_status,accessibility_status,release_status,source_uri,sha256,updated_at&order=updated_at.desc")}}
async function registerBook(b:Row){const slug=text(b.slug,140).toLowerCase(),title=text(b.title,300);if(!slug||!title||!/^[a-z0-9][a-z0-9-]*$/.test(slug))throw Error("valid_slug_and_title_required");const rows=await upsert("penta_books",{slug,title,universe:text(b.universe,240)||null,series:text(b.series,240)||null,book_number:integer(b.book_number),creator:text(b.creator,200)||"Kavonte Jones Sr.",imprint:text(b.imprint,200)||"Virality Music by CrownThrive",owner:text(b.owner,200)||"CrownThrive LLC",canonical_status:text(b.canonical_status,40)||"governed",maturity:text(b.maturity,40)||"active",metadata:obj(b.metadata),updated_at:new Date().toISOString()},"slug");const book=rows?.[0];await event("book.registered","book",String(book?.id??slug),{slug,title});return{ok:true,book}}
async function registerEdition(b:Row){const book_id=id(b.book_id),version=text(b.version,80),edition_name=text(b.edition_name,260),format=text(b.format,40)||"pdf";if(!version||!edition_name)throw Error("version_and_edition_name_required");const rows=await upsert("penta_book_editions",{book_id,version,edition_name,format,status:text(b.status,40)||"draft",vm_standard:text(b.vm_standard,40)||"VM-BOOK-001",source_uri:text(b.source_uri,1000)||null,sha256:text(b.sha256,128)||null,page_count:integer(b.page_count),word_count:integer(b.word_count),illustration_count:integer(b.illustration_count),rights_status:text(b.rights_status,40)||"review_required",accessibility_status:text(b.accessibility_status,40)||"review_required",release_status:text(b.release_status,40)||"not_ready",metadata:obj(b.metadata),updated_at:new Date().toISOString()},"book_id,version,edition_name,format");const edition=rows?.[0];await event("book.edition.registered","edition",String(edition?.id??book_id),{version,edition_name,format});return{ok:true,edition}}
async function appendCanon(b:Row){const fact_key=text(b.fact_key,240),namespace=text(b.namespace,180)||"global";if(!fact_key||b.fact_value===undefined)throw Error("fact_key_and_fact_value_required");const source_ref=text(b.source_ref,1000);if(!source_ref)throw Error("source_ref_required");const rows=await post("penta_canon_facts",{book_id:b.book_id?id(b.book_id):null,namespace,fact_key,fact_value:b.fact_value,status:text(b.status,40)||"fixed",source_type:text(b.source_type,80)||"project_source",source_ref,source_locator:text(b.source_locator,500)||null,source_rank:integer(b.source_rank,50),supersedes:b.supersedes?id(b.supersedes):null,effective_from:new Date().toISOString()});const fact=rows?.[0];await event("book.canon.appended","canon_fact",String(fact?.id??fact_key),{namespace,fact_key,status:fact?.status});return{ok:true,fact}}
async function qa(b:Row){const edition_id=id(b.edition_id),standard_id=text(b.standard_id,60),gate_id=text(b.gate_id,120),status=text(b.status,30);if(!standard_id||!gate_id||!["pass","fail","hold","waived"].includes(status))throw Error("edition_id_standard_gate_valid_status_required");const rows=await post("penta_book_qa_runs",{edition_id,standard_id,gate_id,status,score:b.score==null?null:Number(b.score),findings:obj(b.findings),evidence_uri:text(b.evidence_uri,1000)||null,signed_off_by:text(b.signed_off_by,240)||null,signed_off_at:b.signed_off_by?new Date().toISOString():null});const receipt=rows?.[0];await event(`book.qa.${status}`,"edition",edition_id,{standard_id,gate_id,qa_id:receipt?.id??null});return{ok:true,qa:receipt}}
async function preflight(b:Row){const edition_id=id(b.edition_id),ed=(await get(`penta_book_editions?id=eq.${encodeURIComponent(edition_id)}&select=*`))?.[0];if(!ed)throw Error("edition_not_found");const st=(await get(`penta_book_standards?standard_id=eq.${encodeURIComponent(ed.vm_standard)}&select=*`))?.[0];if(!st)throw Error("standard_not_found");const runs:Row[]=await get(`penta_book_qa_runs?edition_id=eq.${encodeURIComponent(edition_id)}&select=gate_id,status,run_at&order=run_at.desc`),latest=new Map<string,string>();for(const r of runs??[])if(!latest.has(r.gate_id))latest.set(r.gate_id,r.status);const gates:string[]=Array.isArray(st.mandatory_gates)?st.mandatory_gates:[],missing=gates.filter(g=>!latest.has(g)),failed=gates.filter(g=>latest.has(g)&&!["pass","waived"].includes(String(latest.get(g)))),hard:string[]=[];if(ed.rights_status!=="cleared")hard.push("rights_not_cleared");if(!["pass","complete","cleared"].includes(String(ed.accessibility_status)))hard.push("accessibility_not_complete");if(!ed.source_uri||!ed.sha256)hard.push("source_or_checksum_missing");const ready=!missing.length&&!failed.length&&!hard.length;await event(ready?"book.release.preflight.passed":"book.release.preflight.failed","edition",edition_id,{standard:st.standard_id,missing,failed,hard});return{ok:true,edition_id,standard:st.standard_id,release_ready:ready,mandatory_gates:gates,missing_gates:missing,nonpassing_gates:failed,hard_blocks:hard}}
Deno.serve(async(req:Request)=>{try{const url=new URL(req.url),p=url.pathname;if(req.method==="GET"){if(p.endsWith("/health")||p.endsWith("/penta-books-control"))return out(200,await health());if(p.endsWith("/catalog"))return out(200,await catalog());if(p.endsWith("/standards"))return out(200,{ok:true,standards:await get("penta_book_standards?select=*&order=effective_date.asc")});return out(404,{ok:false,error:"route_not_found"})}if(req.method!=="POST")return out(405,{ok:false,error:"method_not_allowed"});const b=obj(await req.json().catch(()=>({}))),a=text(b.action,80);const r=a==="book.register"?await registerBook(b):a==="edition.register"?await registerEdition(b):a==="canon.append"?await appendCanon(b):a==="qa.record"?await qa(b):a==="release.preflight"?await preflight(b):a==="event.append"?{ok:true,event:await event(text(b.event_type,120),text(b.aggregate_type,80),text(b.aggregate_id,160),obj(b.payload))}:a==="health"?await health():null;return r?out(200,r):out(400,{ok:false,error:"unsupported_action"})}catch(e){return out(400,{ok:false,service:SERVICE,version:VERSION,error:e instanceof Error?e.message:"internal_error"})}});
export {};
